version: '3'

services:
  naat-docs:
    image: naat-docs
    container_name: naat-docs
    hostname: naat-docs
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    user: vscode
    volumes:
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gnupg:/home/vscode/.gnupg
      - ..:/app
    env_file:
      - devcontainer.env
    command: sleep infinity